version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pukaar-backend
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pukaar-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://34.47.240.92:5000
    restart: unless-stopped 